image: docker:latest

before_script:
  - apk add --no-cache python3 libffi-dev openssl-dev gcc libc-dev make 
  - python3 --version
  - sh install.sh
  
stages:
  - test
  - deploy

test:
  stage: test
  script: echo "[Test gitlab-ci] On teste l'application eNews"

deploy:
  stage: deploy
  only:
  - master
  script:
  - echo "[Test gitlab-ci] On déploie l'application eNews"
