image: 
  name: docker:latest
  entrypoint: [""]


before_script:
  - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
 
install:
  only: 
    - master
  script:
    - sh install.sh